server:
  port: ${PORT:8080}
  address: 0.0.0.0
spring:
  application:
    name: stock_manager

  datasource:
    url: jdbc:mysql://mysql-db:3306/stock_db
    #   url: jdbc:mysql://localhost:3306/stock_db
    username: jospin
    password: joe@8452
    #    username: root
    #    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
